name = "zach-terminal"
type = "javascript"

account_id = "your_account_id_here"
workers_dev = true
compatibility_date = "2025-04-30"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "echo Static deployment — no build needed"
